"""
plan_intent.py — lightweight detection of a user PLAN statement for the what-if/plans
feature: is this a plan (or a "no plans") statement, and is it SPARSE (an activity with
no specifics) or SPECIFIC (a named place/destination)?

Regex first-pass (fast, on the reply hot path), with an OPTIONAL local-qwen confirm that
refines sparse-vs-specific when the regex is unsure (qwen is the project's sanctioned
cheap classifier — never the cloud model on this path). Fully failure-safe: any error
degrades to the regex result, and the caller treats a classification failure as "fall
back to the generic plan acknowledgment" (no regression).

This module makes a JUDGMENT only — it never writes user-facing text. The reply itself
is generated by the main model from the directive the agenda builds.
"""

from __future__ import annotations

import logging
import re

import config

_log = logging.getLogger(__name__)

# "I have no plans / nothing going on / free this weekend" → suggest something to do.
_NO_PLANS_PAT = re.compile(
    r"\b(?:no plans?(?:\s+(?:yet|so far|really))?|nothing (?:planned|going on|much|on)|"
    r"not (?:doing|up to|got) (?:anything|much)|free (?:this )?(?:weekend|day|week|tonight|"
    r"tomorrow)|wide open|nothing on the books|got nothing (?:going|planned|on)?)\b",
    re.IGNORECASE,
)

# Travel / activity verbs that signal a real plan.
_PLAN_VERB_PAT = re.compile(
    r"\b(?:going|heading|traveling|travelling|flying|driving|visiting|leaving|coming|"
    r"meeting|camping|hiking|skiing|snowboarding|fishing|surfing|backpacking|road[\s-]?trip|"
    r"hitting up)\b",
    re.IGNORECASE,
)

# Time-frame words that, with a plan verb or activity, mark an upcoming plan.
_TIME_PAT = re.compile(
    r"\b(?:tomorrow|tonight|this weekend|next weekend|next week|"
    r"(?:this|next|on)\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday))\b",
    re.IGNORECASE,
)

# Mundane "going to <X>" idioms that are NOT travel plans — so Rex never asks
# "where are you going to bed?". These fall back to the generic acknowledgment.
_NONPLAN_PAT = re.compile(
    r"\bgoing to\s+(?:bed|sleep|be\b|try|get|grab|make|have|need|do|say|tell|ask|check|"
    r"start|finish|work|the (?:bathroom|restroom|toilet|kitchen|fridge|store|gym|office))\b|"
    r"\bgoing (?:crazy|nuts|insane|blind|deaf|gray|grey|bald|broke)\b",
    re.IGNORECASE,
)

# A SPECIFIC destination: a preposition followed by a proper-noun phrase
# ("to Yosemite", "at the American River", "up to Tahoe").
_PLACE_PAT = re.compile(
    r"\b(?:to|at|in|near|up to|down to|over to|out to|around)\s+"
    r"(?:the\s+)?([A-Z][A-Za-z'’.&-]+(?:\s+[A-Z][A-Za-z'’.&-]+){0,3})"
)
_DAYS = {
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
}
_PLACE_FALSE_POSITIVES = _DAYS | {"i", "i'm", "im", "rex", "god", "today", "tomorrow"}

_ACTIVITY_PAT = re.compile(
    r"\b(?:going|heading|planning)\s+(?:to\s+|on\s+(?:a\s+)?)?(?:go\s+)?([a-z]{3,}(?:ing)?)\b",
    re.IGNORECASE,
)
_GENERIC_ACTIVITY = {
    "the", "to", "go", "going", "heading", "planning", "out", "off", "for", "with",
    "traveling", "travelling", "visiting", "meeting", "coming", "leaving", "driving",
    "flying", "see", "get", "have",
}


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", (text or "").lower()).strip()


def _extract_activity(text: str) -> str:
    m = _ACTIVITY_PAT.search(text)
    activity = (m.group(1).lower() if m else "")
    if activity in _GENERIC_ACTIVITY:
        activity = ""
    if not activity:
        for g in re.findall(r"\b([a-z]{4,}ing)\b", text.lower()):
            if g not in _GENERIC_ACTIVITY:
                activity = g
                break
    return activity


def _extract_place(text: str) -> str:
    m = _PLACE_PAT.search(text)
    if not m:
        return ""
    place = m.group(1).strip()
    if place.split()[0].lower() in _PLACE_FALSE_POSITIVES:
        return ""
    return place


def classify(text: str) -> dict:
    """Return {is_plan, is_no_plans, specificity('sparse'|'specific'), place, activity,
    plan_key}. plan_key is a coarse per-plan dedupe handle. Never raises."""
    out = {
        "is_plan": False, "is_no_plans": False, "specificity": "sparse",
        "place": "", "activity": "", "plan_key": "plan",
    }
    t = (text or "").strip()
    if not t:
        return out
    try:
        if _NO_PLANS_PAT.search(t):
            out["is_no_plans"] = True
            out["plan_key"] = "no_plans"
            return out
        if _NONPLAN_PAT.search(t) and not _PLACE_PAT.search(t):
            return out  # mundane "going to bed" etc. → not a plan
        if not (_PLAN_VERB_PAT.search(t) or _TIME_PAT.search(t)):
            return out
        out["is_plan"] = True
        out["activity"] = _extract_activity(t)
        out["place"] = _extract_place(t)
        specific = bool(out["place"])
        if not specific and _qwen_confirm_enabled():
            specific = _qwen_is_specific(t)
        out["specificity"] = "specific" if specific else "sparse"
        out["plan_key"] = _norm(out["activity"]) or _norm(out["place"]) or "plan"
        return out
    except Exception as exc:
        _log.debug("[plan_intent] classify failed: %s", exc)
        # Clean, fully-safe default → caller uses the generic acknowledgment (no risk).
        return {
            "is_plan": False, "is_no_plans": False, "specificity": "sparse",
            "place": "", "activity": "", "plan_key": "plan",
        }


def _qwen_confirm_enabled() -> bool:
    return bool(getattr(config, "PLAN_INTENT_QWEN_CONFIRM_ENABLED", True))


def _qwen_is_specific(text: str) -> bool:
    """Ask the local qwen sidecar whether a SPECIFIC place/destination/event was named
    (catches lowercase or unusual place names the regex misses). Failure → False, so the
    safe default is 'sparse' → ask a clarifying question rather than bluff a suggestion."""
    try:
        from intelligence import local_llm
        if not local_llm.enabled():
            return False
        raw = local_llm.generate(
            f'Sentence: "{text}"\n'
            "Did they name a SPECIFIC place, destination, or event (not just a vague "
            "activity like 'camping')? Answer yes or no.",
            system="You are a terse classifier. Reply with only 'yes' or 'no'.",
            temperature=0.0,
            max_tokens=2,
            timeout_secs=float(getattr(config, "PLAN_INTENT_QWEN_TIMEOUT_SECS", 0.9)),
        )
        return (raw or "").strip().lower().startswith("y")
    except Exception as exc:
        _log.debug("[plan_intent] qwen confirm failed: %s", exc)
        return False
